"""Spark integration test for involved_party_electronic_address dbt model.
Auto-generated by dbt Job Generator.
"""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal

import pytest
from pyspark.sql import SparkSession

from fake_data_factory import register_fake_table
from sql_test_helper import prepare_sql

TEST_DATE = date(2024, 1, 1)

FAKE_THONG_TIN_DK_THUE = [
    {"id": 1, "email_kd": "test_value_1", "fax_kd": "test_value_1", "fax": "test_value_1", "dien_thoai_kd": "test_value_1", "dien_thoai": "test_value_1", "data_date": date(2024, 1, 1)},
    {"id": 2, "email_kd": "test_value_2", "fax_kd": "test_value_2", "fax": "test_value_2", "dien_thoai_kd": "test_value_2", "dien_thoai": "test_value_2", "data_date": date(2023, 12, 31)},
]

FAKE_TTKDT_NGUOI_DAI_DIEN = [
    {"id": 1, "email": "test_value_1", "fax": "test_value_1", "dien_thoai": "test_value_1", "data_date": date(2024, 1, 1)},
    {"id": 2, "email": "test_value_2", "fax": "test_value_2", "dien_thoai": "test_value_2", "data_date": date(2023, 12, 31)},
]

GENERATED_SQL = """\
WITH th_ti_dk_th AS (
    SELECT id, email_kd, fax_kd, fax, dien_thoai_kd, dien_thoai, 'DCST_THONG_TIN_DK_THUE' AS source_system_code
    FROM THONG_TIN_DK_THUE
    WHERE data_date = to_date('2024-01-01', 'yyyy-MM-dd')
),

leg_th_ti_dk_th AS (
    SELECT
        id AS ip_code,
        'EMAIL' AS type_code,
        email_kd AS address_value,
        source_system_code
    FROM th_ti_dk_th
    WHERE email_kd IS NOT NULL
    UNION ALL
    SELECT
        id AS ip_code,
        'FAX' AS type_code,
        fax_kd AS address_value,
        source_system_code
    FROM th_ti_dk_th
    WHERE fax_kd IS NOT NULL
    UNION ALL
    SELECT
        id AS ip_code,
        'FAX' AS type_code,
        fax AS address_value,
        source_system_code
    FROM th_ti_dk_th
    WHERE fax IS NOT NULL
    UNION ALL
    SELECT
        id AS ip_code,
        'PHONE' AS type_code,
        dien_thoai_kd AS address_value,
        source_system_code
    FROM th_ti_dk_th
    WHERE dien_thoai_kd IS NOT NULL
    UNION ALL
    SELECT
        id AS ip_code,
        'PHONE' AS type_code,
        dien_thoai AS address_value,
        source_system_code
    FROM th_ti_dk_th
    WHERE dien_thoai IS NOT NULL
),

tt_ng_da_di AS (
    SELECT id, email, fax, dien_thoai, 'DCST_TTKDT_NGUOI_DAI_DIEN' AS source_system_code
    FROM TTKDT_NGUOI_DAI_DIEN
    WHERE data_date = to_date('2024-01-01', 'yyyy-MM-dd')
),

leg_tt_ng_da_di AS (
    SELECT
        id AS ip_code,
        'EMAIL' AS type_code,
        email AS address_value,
        source_system_code
    FROM tt_ng_da_di
    WHERE email IS NOT NULL
    UNION ALL
    SELECT
        id AS ip_code,
        'FAX' AS type_code,
        fax AS address_value,
        source_system_code
    FROM tt_ng_da_di
    WHERE fax IS NOT NULL
    UNION ALL
    SELECT
        id AS ip_code,
        'PHONE' AS type_code,
        dien_thoai AS address_value,
        source_system_code
    FROM tt_ng_da_di
    WHERE dien_thoai IS NOT NULL
)

SELECT
    sha2(concat_ws('|', leg_th_ti_dk_th.source_system_code, CAST(leg_th_ti_dk_th.ip_code AS STRING)), 256) AS involved_party_id,
    CAST(leg_th_ti_dk_th.ip_code AS string)                                    AS involved_party_code,
    CAST(leg_th_ti_dk_th.source_system_code AS string)                         AS source_system_code,
    CAST(leg_th_ti_dk_th.type_code AS string)                                  AS electronic_address_type_code,
    CAST(leg_th_ti_dk_th.address_value AS string)                              AS electronic_address_value
FROM leg_th_ti_dk_th
UNION ALL
SELECT
    sha2(concat_ws('|', leg_tt_ng_da_di.source_system_code, CAST(leg_tt_ng_da_di.ip_code AS STRING)), 256) AS involved_party_id,
    CAST(leg_tt_ng_da_di.ip_code AS string)                                    AS involved_party_code,
    CAST(leg_tt_ng_da_di.source_system_code AS string)                         AS source_system_code,
    CAST(leg_tt_ng_da_di.type_code AS string)                                  AS electronic_address_type_code,
    CAST(leg_tt_ng_da_di.address_value AS string)                              AS electronic_address_value
FROM leg_tt_ng_da_di

"""

EXPECTED_COLUMNS = [
    "involved_party_id",
    "involved_party_code",
    "source_system_code",
    "electronic_address_type_code",
    "electronic_address_value",
]

@pytest.fixture(autouse=True)
def setup_source_tables(spark: SparkSession):
    register_fake_table(spark, "THONG_TIN_DK_THUE", FAKE_THONG_TIN_DK_THUE)
    register_fake_table(spark, "TTKDT_NGUOI_DAI_DIEN", FAKE_TTKDT_NGUOI_DAI_DIEN)

class TestInvolvedPartyElectronicAddressSpark:
    def test_sql_executes_without_error(self, spark: SparkSession):
        result = spark.sql(GENERATED_SQL)
        assert result is not None

    def test_output_has_correct_columns(self, spark: SparkSession):
        result = spark.sql(GENERATED_SQL)
        assert result.columns == EXPECTED_COLUMNS

    def test_has_rows(self, spark: SparkSession):
        result = spark.sql(GENERATED_SQL)
        assert result._jdf.count() > 0
