"""Spark integration test for fund_management_company dbt model.
Auto-generated by dbt Job Generator.
"""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal

import pytest
from pyspark.sql import SparkSession

from fake_data_factory import register_fake_table
from sql_test_helper import prepare_sql

TEST_DATE = date(2024, 1, 1)

FAKE_FUNDCOMPANY = [
    {"id": 1, "name": "test_value_1", "shortname": "test_value_1", "ename": "test_value_1", "capital": Decimal("100.00"), "createdby": "test_value_1", "datecreated": datetime(2024, 1, 1), "datemodified": datetime(2024, 1, 1), "naid": 1, "statusid": 1, "director": "test_value_1", "depcert": "test_value_1", "description": "test_value_1", "data_date": date(2024, 1, 1)},
    {"id": 2, "name": "test_value_2", "shortname": "test_value_2", "ename": "test_value_2", "capital": Decimal("200.00"), "createdby": "test_value_2", "datecreated": datetime(2024, 1, 2), "datemodified": datetime(2024, 1, 2), "naid": 2, "statusid": 2, "director": "test_value_2", "depcert": "test_value_2", "description": "test_value_2", "data_date": date(2023, 12, 31)},
]

FAKE_FUNDCOMBUSINES = [
    {"fundid": 1, "buid": 1, "data_date": date(2024, 1, 1)},
    {"fundid": 2, "buid": 2, "data_date": date(2023, 12, 31)},
]

FAKE_FUNDCOMTYPE = [
    {"fundid": 1, "comtypeid": 1, "data_date": date(2024, 1, 1)},
    {"fundid": 2, "comtypeid": 2, "data_date": date(2023, 12, 31)},
]

GENERATED_SQL = """\
WITH fu_co AS (
    SELECT id, name, shortname, ename, capital, createdby, datecreated, datemodified, naid, statusid, director, depcert, description
    FROM FUNDCOMPANY
    WHERE data_date = to_date('2024-01-01', 'yyyy-MM-dd')
)

SELECT
    sha2(concat_ws('|', 'FIMS_FUNDCOMPANY', CAST(fu_co.id AS STRING)), 256) AS fund_management_company_id,
    CAST(fu_co.id AS string)                    AS fund_management_company_code,
    CAST('FIMS_FUNDCOMPANY' AS string)          AS source_system_code,
    CAST(fu_co.name AS string)                  AS fund_management_company_name,
    CAST(fu_co.shortname AS string)             AS fund_management_company_short_name,
    CAST(fu_co.ename AS string)                 AS fund_management_company_english_name,
    CAST(NULL AS string)                        AS practice_status_code,
    CAST(fu_co.capital AS decimal(23,2))        AS charter_capital_amount,
    CAST(NULL AS string)                        AS dorf_indicator,
    CAST(NULL AS string)                        AS license_decision_number,
    CAST(NULL AS date)                          AS license_decision_date,
    CAST(NULL AS date)                          AS active_date,
    CAST(NULL AS date)                          AS stop_date,
    CAST(NULL AS string)   AS business_type_codes,
    CAST(fu_co.createdby AS string)             AS created_by,
    CAST(fu_co.datecreated AS timestamp)        AS created_timestamp,
    CAST(fu_co.datemodified AS timestamp)       AS updated_timestamp,
    sha2(concat_ws('|', 'FIMS_NATIONAL', CAST(fu_co.naid AS STRING)), 256)  AS country_of_registration_id,
    CAST(fu_co.naid AS string)                  AS country_of_registration_code,
    CAST(fu_co.statusid AS string)              AS life_cycle_status_code,
    CAST(fu_co.director AS string)              AS director_name,
    CAST(fu_co.depcert AS string)               AS depository_certificate_number,
    CAST(NULL AS string)    AS company_type_codes,
    CAST(fu_co.description AS string)           AS description,
    CAST(NULL AS string)                        AS company_type_code,
    CAST(NULL AS string)                        AS fund_type_code,
    CAST(NULL AS string)                        AS business_license_number,
    CAST(NULL AS string)                        AS website
FROM fu_co

"""

EXPECTED_COLUMNS = [
    "fund_management_company_id",
    "fund_management_company_code",
    "source_system_code",
    "fund_management_company_name",
    "fund_management_company_short_name",
    "fund_management_company_english_name",
    "practice_status_code",
    "charter_capital_amount",
    "dorf_indicator",
    "license_decision_number",
    "license_decision_date",
    "active_date",
    "stop_date",
    "business_type_codes",
    "created_by",
    "created_timestamp",
    "updated_timestamp",
    "country_of_registration_id",
    "country_of_registration_code",
    "life_cycle_status_code",
    "director_name",
    "depository_certificate_number",
    "company_type_codes",
    "description",
    "company_type_code",
    "fund_type_code",
    "business_license_number",
    "website",
]

@pytest.fixture(autouse=True)
def setup_source_tables(spark: SparkSession):
    register_fake_table(spark, "FUNDCOMPANY", FAKE_FUNDCOMPANY)
    register_fake_table(spark, "FUNDCOMBUSINES", FAKE_FUNDCOMBUSINES)
    register_fake_table(spark, "FUNDCOMTYPE", FAKE_FUNDCOMTYPE)

class TestFundManagementCompanySpark:
    def test_sql_executes_without_error(self, spark: SparkSession):
        result = spark.sql(GENERATED_SQL)
        assert result is not None

    def test_output_has_correct_columns(self, spark: SparkSession):
        result = spark.sql(GENERATED_SQL)
        assert result.columns == EXPECTED_COLUMNS

    def test_has_rows(self, spark: SparkSession):
        result = spark.sql(GENERATED_SQL)
        assert result._jdf.count() > 0
